version: "3.8"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: User
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVERIMODE: 'False'
    ports:
      - "5050:80"